import '../styles/globals.css'
import Head from 'next/head'
import { RoomProvider } from '../Context/RoomContext'
import { SessionProvider } from 'next-auth/react'

function MyApp ({ Component, pageProps }) {
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  return (
    <SessionProvider>
      <RoomProvider>
        <Component {...pageProps} />
      </RoomProvider>
    </SessionProvider>
  )
}

export default MyApp
